version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
environment:
  nuget_api_key:
    secure: a/a+mCGBoKlFFuQt0Fi6PsYb5r6LtYZK3Mu0iDKCby4vHNGWzhTywNAhNR8I9xMt
install:
- cmd: choco install gitversion.portable -pre -y
before_build:
- cmd: >-
    dotnet restore

    gitversion /l console /output buildserver /updateAssemblyInfo NHibernate.logging.serilog\AssemblyInfo.cs /ensureassemblyinfo
build:
  verbosity: normal
after_build:
- cmd: dotnet pack "NHibernate.Logging.Serilog\NHibernate.Logging.Serilog.csproj" -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets /p:Version=%GitVersion_NuGetVersion%
artifacts:
- path: nugets\*.*nupkg
  name: NuGet Package
deploy:
- provider: NuGet
  api_key:
    secure: a/a+mCGBoKlFFuQt0Fi6PsYb5r6LtYZK3Mu0iDKCby4vHNGWzhTywNAhNR8I9xMt
  on:
    branch: master
    APPVEYOR_REPO_TAG: True
after_deploy:
- ps: Get-ChildItem .\nugets\*.snupkg | % { dotnet nuget push $_.FullName -s https://api.nuget.org/v3/index.json -k $env:nuget_api_key }
